[versions]
kotlin = "2.2.0"
gradle-android = "8.13.0"
gradle-jvmToolchain = "21"
agp = "8.7.3"

[libraries]
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
android-gradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.7.0" }
androidx-lifecycle = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version = "2.9.1" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version = "2025.10.00" }
compose-activity = { module = "androidx.activity:activity-compose", version = "1.11.0" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-uiTooling = { module = "androidx.compose.ui:ui-tooling" }

[bundles]
compose = ["compose-activity", "compose-material3", "compose-uiTooling"]

[plugins]
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "gradle-android" }
android-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "gradle-android" }
publish = { id = "com.gradle.plugin-publish", version = "2.0.0" }
vanniktech-maven-publish = { id = "com.vanniktech.maven.publish", version = "0.28.0" }
