[versions]
kotlin = "2.2.0"
gradle-android = "8.13.2"
gradle-jvmToolchain = "21"
agp = "8.7.3"

[libraries]
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
android-gradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }

[plugins]
vanniktech-maven-publish = { id = "com.vanniktech.maven.publish", version = "0.35.0" }
